module D_oom
  PLAYER_SPEED_Z         =  1
  PLAYER_SPEED_X         =  1
  PLAYER_FOV             = 45
  PLAYER_VIEWPORT_X      = (WINDOW_RES_X/2) - (PLAYER_VIEWPORT_WIDTH/2)
  PLAYER_VIEWPORT_Y      = (WINDOW_RES_Y/2) - (PLAYER_VIEWPORT_HEIGHT/2)
  PLAYER_VIEWPORT_WIDTH  = 800
  PLAYER_VIEWPORT_HEIGHT = 600

  FOV_BASE_WIDTH  = 4
  FOV_BASE_HEIGHT = 3

  WINDOW_RES_X = 1024
  WINDOW_RES_Y =  768

  VIEWPORT_RES_X = 800
  VIEWPORT_RES_Y = 600
end
